site_name: Bioinformatics
site_url: http://bioinformatics.readthedocs.io/
site_description: The Bioinformatics Core Facility at the Donald Danforth Plant Science Center
site_author: Bioinformatics
repo_url: https://github.com/danforthcenter/bioinformatics
copyright: Copyright 2016, Donald Danforth Plant Science Center

pages:
- Home: index.md
- Documentation:
  - "Getting started": gettingstarted.md
  - "Usage policies": policies.md
  - "Cluster overview": cluster_overview.md
  - "Data sharing with Globus": globus.md
  - "HTCondor user's guide":
    - "Overview": htcondor_overview.md
    - "Running jobs": htcondor_running_jobs.md
    - "Other commands & troubleshooting": htcondor_commands_troubleshooting.md
  - "Bioinformatics software":
    - "ALLPATHS-LG": allpaths.md
    - "Aspera-Connect": aspera.md
    - "Augustus": augustus.md
    - "Bamtools": bamtools.md
    - "BBTools": bbtools.md
    - "Bowtie": bowtie.md
    - "Bowtie2": bowtie2.md
    - "BRAKER": braker.md
    - "BUSCO": busco.md
    - "CNVnator": cnvnator.md
    - "Gffread": gffread.md
    - "HISAT2": hisat2.md
    - "Kallisto": kallisto.md
    - "NCBI BLAST+": blast.md
    - "Salmon": salmon.md
    - "SHORE": shore.md
    - "SPAdes": spades.md
    - "SRA-Tools": sratools.md
    - "Supernova": supernova.md
    - "Trinity": trinity.md
    - "UCSC Tools": kent.md
    - "Variation Graph": vg.md
    - "VarScan": varscan.md

markdown_extensions:
  - toc:
      permalink: True
  - sane_lists
