site_name: Bioinformatics
site_url: http://bioinformatics.readthedocs.io/
site_description: The Bioinformatics Core Facility at the Donald Danforth Plant Science Center
site_author: Bioinformatics
repo_url: https://github.com/danforthcenter/bioinformatics
copyright: Copyright 2016, Donald Danforth Plant Science Center

pages:
- Home: index.md
- Documentation:
  - "Cluster overview": cluster_overview.md
  - "Data sharing with Globus": globus.md
  - "HTCondor user's guide":
    - "Overview": htcondor_overview.md
    - "Getting started": htcondor_getting_started.md
    - "Running jobs": htcondor_running_jobs.md
  - "Bioinformatics software":
    - "ALLPATHS-LG": allpaths.md
    - "Aspera-Connect": aspera.md
    - "Augustus": augustus.md
    - "Bamtools": bamtools.md
    - "Bowtie2": bowtie2.md
    - "BUSCO": busco.md
    - "Kallisto": kallisto.md
    - "NCBI BLAST+": blast.md
    - "Salmon": salmon.md
    - "SRA-Tools": sratools.md
    - "Trinity": trinity.md
    - "UCSC Tools": kent.md

markdown_extensions:
  - toc:
      permalink: True
