#!/bin/bash

old_DISPLAY=$DISPLAY
export DISPLAY=:0

args=$@
/usr/local/bin/singularity exec /bioinfo/singularity/dirt.img /bin/bash -c "python /bioinfo/tools/bioinformatics/scripts/dirt_apply_threshold.py ${args}"

export DISPLAY=$old_DISPLAY
